### PR TITLE
Make iOS scanner UI look the same as Android

### PR DESCRIPTION
**Pull request by dustin-graham**
adds a semi-transparent overlay, scan window, and pulsing scan line.

### CODE REVIEW

**Comment by dustin-graham** [comment]
@matthewtsmith, what do you think?

**Comment by dustin-graham** [comment]
@matthewtsmith ping. I'd like to see if we can merge this in so my app no longer needs to point to my fork for this functionality.

**Comment by bhammer88** [comment]
I'll be happy to use this as well

**Comment by victoraugustolls** [comment]
Looking forward to this!

**Comment by bhammer88** [comment]
can your fork make it work with dart 2.1.0?

**Comment by victoraugustolls** [comment]
@matthewtsmith any news here to merge this pull request?

**Comment by dustin-graham** [comment]
I don't know right now I haven't tried. Nothing in the dart changelog
strikes me as a problem though.
https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md. do you know of
any specific incompatibilities?

**Comment by victoraugustolls** [comment]
@dustin-graham as far as I know, now with beta 6 flutter recommendation is to set dart upper bound to 3.0.0! There should be no issues!

See:
https://github.com/flutter/flutter/wiki/Changelog

**Comment by matthewtsmith** [comment]
Sorry... took me a while to get chance to run this project and test it out. This looks ready to go from my testing.

**Pull request merged**
