### PR TITLE
Rewrite platform communication

### LINKED ISSUE #53: Issues with camera resolution on HUAWAI Mate 8
When using the BarcodeScanner.scan() method on the Huawai Mate 8, the automatic resolution detection sets the resolution too low, so no barcodes are found. Is there a way to set the resolution manually?

### LINKED ISSUE #85: Headless background task can not be executed if barcode library is embeded
Hi,
i have a problem using the library background_fetch (background_fetch: '^0.1.0') when I embed the barcode library.
I get the following exception if my background task starts:

java.lang.RuntimeException: java.lang.IllegalStateException: registrar.activity() must not be null
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)                                                             
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:108)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:166)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7425)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
02-25 11:32:42.472 11461 11461 E AndroidRuntime: Caused by: java.lang.IllegalStateException: registrar.activity() must not be null
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.apptreesoftware.barcodescan.BarcodeScanPlugin$Companion.registerWith(BarcodeScanPlugin.kt:19)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.apptreesoftware.barcodescan.BarcodeScanPlugin.registerWith(Unknown Source:2)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:22)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.example.xyz.Application.registerWith(Application.java:17)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.initFlutterView(HeadlessTask.java:133)
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.<init>(HeadlessTask.java:47)                                                             
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessJobService.onStartJob(HeadlessJobService.java:38)                                             
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.app.job.JobService$1.onStartJob(JobService.j
02-25 11:32:42.472 11461 11461 E AndroidRuntime:        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java)

See also Issue:
https://github.com/transistorsoft/flutter_background_fetch/issues/12

### LINKED ISSUE #91: Localize the Flash On/Off button would be better
The **Flash On/Off** button text is hard coded now, localize it would be better.

https://github.com/apptreesoftware/flutter_barcode_reader/blob/5d498e39a76466b03579486475ec777fba33ed2c/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScannerActivity.kt#L39

https://github.com/apptreesoftware/flutter_barcode_reader/blob/5d498e39a76466b03579486475ec777fba33ed2c/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScannerActivity.kt#L43

https://github.com/apptreesoftware/flutter_barcode_reader/blob/5e360fc9dad8f3525e75aaaf6e7d64490759eda2/ios/Classes/BarcodeScannerViewController.m#L93

https://github.com/apptreesoftware/flutter_barcode_reader/blob/5e360fc9dad8f3525e75aaaf6e7d64490759eda2/ios/Classes/BarcodeScannerViewController.m#L97

### LINKED ISSUE #113: Devices with infrared scanner integrated.
We've built an app that runs on multiple kinds of devices,  there are some of them with integrated infrared scanner.
On those devices the plugin is unable to open the camera, most likely the scanner is set as the first background camera. 

So my request is to have the chance to set the camera to use or/and  get some variable where we can check if the plugin got the camera connection.

### LINKED ISSUE #131: return com.google.zxing.Result type object instead of only string
in order to have also information about the type of barcode

### LINKED ISSUE #169: Only Barcode
Hello, How can I specified only barcode feature?, in my App I don't need Scan QR.

### LINKED ISSUE #200: can we return also type of of the scan if its BR or QR?

### PR DESCRIPTION
**Pull request by devtronic**
Use this PR to test the new features:

```yaml
# pubspec.yaml
dependencies:
  barcode_scan:
    git:
      url: https://github.com/mintware-de/flutter_barcode_reader.git
      ref: 51affc97580a765f0fa007c0c7fca311db7b119d
```

Usage:
## Advanced usage
You can pass options to the scan method:

```dart

import 'package:barcode_scan/barcode_scan.dart';

void main() async {
  
  var options = ScanOptions(
    // set the options
  );

  var result = await BarcodeScanner.scan(options: options);
  
  // ...
}
```

### Supported options
| Option                     | Type              | Description                                                                               | Supported by  |
|----------------------------|-------------------|-------------------------------------------------------------------------------------------|---------------|
| `strings.cancel`           | `String`          | The cancel button text on iOS                                                             | iOS only      |
| `strings.flash_on`         | `String`          | The flash on button text                                                                  | iOS + Android |
| `strings.flash_off`        | `String`          | The flash off button text                                                                 | iOS + Android |
| `restrictFormat`           | `BarcodeFormat[]` | Restrict the formats which are recognized                                                 | iOS + Android |
| `useCamera`                | `int`             | The index of the camera which is used for scanning (See `BarcodeScanner.numberOfCameras`) | iOS + Android |
| `autoEnableFlash`          | `bool`            | Enable the flash when start scanning                                                      | iOS + Android |
| `android.aspectTolerance`  | `double`          | Enable the flash when start scanning                                                      | Android only  |
| `android.useAutoFocus`     | `bool`            | Enable the flash when start scanning                                                      | Android only  |

Todo:
- [x] Set camera properties
- [x] Return the barcode type

### CODE REVIEW

**Comment by phcaraujo** [comment]
Error 

Sem título

**Comment by devtronic** [comment]
Please post the content of your pubspec.yaml and pubspec.lock

**Comment by Skyost** [comment]
When does this pull request will be merged ?

**Comment by sclausen** [comment]
Does/Could this PR also incorporate the config options to solve #53?

**Comment by devtronic** [comment]
I'll try to finalize the PR next week.

@sclausen Yes :-)

**Comment by Skyost** [comment]
Cool !

**Comment by kw2019ltd** [comment]
hi can we return instead of code (future<String>) to return object which contain the code and type (if its QR or Bar..) and if its barcode to return barcode type (pdf,code128 etc)...

static Future<String> scan({Configuration config}) async =>
      await _channel.invokeMethod('scan', config?.writeToBuffer());

**Comment by devtronic** [comment]
@kw2019ltd Of course 🙂

**Comment by ghost** [comment]
Hello，when will 3.x be officially released?

https://pub.dev/packages/barcode_scan#-changelog-tab-

**Comment by devtronic** [comment]
Tomorrow 🙂

**Comment by ghost** [comment]
> Tomorrow 🙂

you are great !

**Comment by ghost** [comment]
Will 3.x support the following feature ?

```

var config = Configuration();
config.cancelText = "Abbrechen"; // Your text for the iOS cancel button 
config.flashOnText = "Blitz an"; // Your text for the Flash On Button
config.flashOffText = "Blitz aus"; // Your text for the Flash Off button
config.restrictFormat.addAll([BarcodeFormat.qr]); // Only scan qr codes

// Camera index. Get it from [BarcodeScanner.numberOfCameras]
config.useCamera = 1;
String barcode = await BarcodeScanner.scan(config: config);
```

**Comment by ghost** [comment]
https://pub.dev/packages/barcode_scan#-changelog-tab-

There is still displaying barcode_scan 2.0.1 version on dart pub.

**Comment by kw2019ltd** [comment]
as mentioned about the PR still not merged to master.

1 comment can you add also barcodeFormat **upca,itf**

**Comment by devtronic** [comment]
@ihihihihihihih It's 9:21 AM in Germany, I'll update the update the library today 😉

@kw2019ltd afaik are this types only supported by the iOS scanner library. IMO the package only should provide options which are supported by both platforms iOS and Android.

**Comment by kw2019ltd** [comment]
good, yes those format are supported by firebase_ml_vision (flutter plugin)
for both android and ios.

**Comment by sclausen** [comment]
@kw2019ltd Unfortunately this lib doesn’t use firebase_ml_vision, but me.dm7.barcodescanner:zxing for android.

**Comment by devtronic** [comment]
@sclausen Yes, but I plan to migrate to ML vision since it provides for both iOS and Android the same options.

**Comment by sclausen** [comment]
Wouldn’t that force developers to have a firebase account for their project to use this library? This seems to be a severe change.

**Comment by ghost** [comment]
3.0.0-dev.2  has a problem on my Android phone.

The plugin on debug mode is ok.

But on release mode has the following error.

```
04-13 11:54:05.966 26938 26977 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method requestCameraPermission on channel de.mintware.barcode_scan)
04-13 11:54:05.966 26938 26977 E flutter : #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319)
04-13 11:54:05.966 26938 26977 E flutter : <asynchronous suspension>
04-13 11:54:05.966 26938 26977 E flutter : #1      BarcodeScanner.scan (package:barcode_scan/platform_wrapper.dart:56)
04-13 11:54:05.966 26938 26977 E flutter : #2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45)
04-13 11:54:05.966 26938 26977 E flutter : #3      BarcodeScanner.scan (package:barcode_scan/platform_wrapper.dart:31)
```

**Comment by devtronic** [comment]
@ihihihihihihih : Take a look on this: https://github.com/mintware-de/flutter_barcode_reader/issues/211

**Pull request merged**
