### PR TITLE
Made Flash On / Off text variable

### PR DESCRIPTION
**Pull request by devtronic**
The text for "Flash On" and "Flash Off" can now be passed to the scan method
`String barcode = await BarcodeScanner.scan("Flash On", "Flash Off");`

- Android only
- Also kotlin version and build tools version updated

### CODE REVIEW

**Comment by devtronic** [comment]
Any reasons why this PR is not getting merged?

**Comment by matthewtsmith** [comment]
Sorry for the slow reply. I have a couple issues with the PR as it stands now.

- We strongly believe that all features should be cross platform. 
- I think the API should take in an `Options` class that can be passed into the `scan()` method. This would allow us to extend the options over time without creating a bunch of arguments in the `scan` method.

The call to open the scanner would look like

`scan(options: new ScanOptions(flashOnText: "Flash On", flashOffText: "Flash Off"))`

The Options class constructor should have reasonable defaults. the `options` should allow null and if so, apply some reasonable defaults.

**Comment by devtronic** [comment]
Thank you for your reply. I'll fix that asap.

**Comment by KamilZielinski** [comment]
@devtronic Are you going to continue work on this API extension?

**Comment by devtronic** [comment]
Hi, yes I've bought a MacBook that I can also extend and test the iOS code.

**Comment by devtronic** [comment]
Please review 🙂

**Comment by devtronic** [comment]
Are my changes ok, @matthewtsmith ? :-)

**Comment by devtronic** [comment]
@matthewtsmith It would be very nice if you could give a short feedback if the changes are good and when you will merge this PR.

**Comment by cristianfb1989** [comment]
Hello everyone! I create the file "scanner_options.dart" 


But in the file "main.dart" does not recognize me the import. 


What can I do to correct the problem? Thank you!

**Pull request closed without merging**
