### PR TITLE
 translate "Flash On" and "Flash Off" to Chinese

### PR DESCRIPTION
**Pull request by JamesKarl**
The label "Flash On" and "Flash Off" are hard-coded currently. I modified that and translated them to Chinese. If other users want to translate these string to their own native language, they can override these strings from their own project.

### CODE REVIEW

**Comment by genert** [comment]
@matthewtsmith

**Comment by glazkovan** [comment]
Russian language required. Can make a passed parameter with these labels?

**Comment by irperera** [comment]
Can you change the Cancel to something else as well?

**Comment by devtronic** [comment]
Thanks for contributing. I'm sorry but the platform communication will be rewritten, which makes your PR incompatible. But from `v3.0` you can pass custom texts for the buttons: #185

**Pull request closed without merging**
